### PR TITLE
chore: re-enable ledger update

### LINKED ISSUE #1521: Fix issue with outdated nodes in genesis blocks
Quite a few IPs are dead in the current genesis blocks. We need to update them to prevent unnecessary delays when using the BC Wallet.

- Fix issue with outdated nodes in genesis blocks.
- Enable genesis block build in CICD pipeline.

### PR DESCRIPTION
**Pull request by jleach**
With the switch to AFJ 4 we had to disable our automatic ldeger updates where we refresh the genesis block to reflect any recent node changes. This PR re-enables this feature.

Ref:

hyperledger/indy-did-networks#3
hyperledger/aries-mobile-agent-react-native#987

Fixed #1521

### CODE REVIEW

**Comment by jleach** [comment]
This PR is in Draft until the Bifold PR noted in the description is merged.

**Review by bryce-mcmath — DISMISSED** [review]

**Comment by bryce-mcmath** [comment]
@cvarjao do you see any issues with the yarn lock file changes here?

**Comment by jleach** [comment]
> @cvarjao do you see any issues with the yarn lock file changes here?

I was getting issues with from yarn install saying the lock file was out of sync so I had to update it:
` YN0028: │ The lockfile would have been modified by this install, which is explicitly forbidden.`

**Review by cvarjao — APPROVED** [review]
I don't see any issues. But we might need to do the same dependency alignment we did for bifold.  But I don't see any red flags. You updated the bifold submodule and it is expected it would change with the new changes to bifold (dependency alignment)

**Pull request merged**
