### PR TITLE
feat: add person credential links

### LINKED ISSUE #1758: Add links to gov.bc.ca Person pages on Person credential screen
### Background/User Story
As a user who received an offer to Get their Person credential in their BC Wallet, I want to know what the Person credential is, so that I can learn more on what it is, where I can use it and find help if I have any issues trying to get it.

### Acceptance Criteria
Given a user has started the Person credential issuance process in BC Wallet
When they are at the [Person credential issuance page in BC Wallet](https://xd.adobe.com/view/50a1d463-0698-4584-a7eb-dfd5ca17be90-05f2/)
Then they are given the option to learn "What is a Person credential"
And they are given the option to contact "Help"

Links will take the user to an external weblink to Person credential gov.bc.ca pages
These links are TBD.

### Wireframes
https://xd.adobe.com/view/50a1d463-0698-4584-a7eb-dfd5ca17be90-05f2/

### PR DESCRIPTION
**Pull request by jleach**
Add the three informative links to the get person screen.

Fixed #1758

image

### CODE REVIEW

**Comment by bryce-mcmath** [comment]
@jleach did you see the comments on the issue this PR is for? Might be worth checking if Kim still wants to hold off on this feature

**Comment by knguyenBC** [comment]
Can the padding on the text be increased to 24dp?

**Comment by jleach** [comment]
@bryce-mcmath No I do now though /:)

I can park this PR for now or add a check that the links get disable if the get your person credential workflow is in progress. I'm fine either way. @knguyenBC

**Comment by jleach** [comment]
> Can the padding on the text be increased to 24dp?

Do you mean the grey between the sections?

**Comment by knguyenBC** [comment]
> > Can the padding on the text be increased to 24dp?
> 
> Do you mean the grey between the sections?

No, between the text and the divider line

**Comment by knguyenBC** [comment]
> @bryce-mcmath No I do now though /:)
> 
> I can park this PR for now or add a check that the links get disable if the get your person credential workflow is in progress. I'm fine either way. @knguyenBC

Please disable the links.

**Review by bryce-mcmath — APPROVED** [review]

**Pull request merged**
