### PR TITLE
feat: credential branding

### PR DESCRIPTION
**Pull request by amanji**
Signed-off-by: Akiff Manji <akiff.manji@gmail.com>

### CODE REVIEW

**Review by wadeking98 — APPROVED** [review]
LGTM

**Comment by swcurran** [comment]
Shouldn’t the template code be in Aries Bifold?  I would think this should be a common feature —especially if/when we OCA enable it.

**Comment by swcurran** [comment]
Obviously anything hardcoded about specific BC credentials shouldn’t be in Bifold.

**Comment by cvarjao** [comment]
@swcurran , there are 2 PRs:
hyperledger/aries-mobile-agent-react-native#413 (in Bifold) and this one.
The Bifold one has the underline template/rendering, this one has the resources of a couple of credentials we are branding.

**Comment by swcurran** [comment]
Good stuff, thanks. I looked on my phone so didn’t really look too closely at the code. Clearly. 🤦

**Pull request merged**
